### ISSUE TITLE
Room for collaboration on edtech elements?

### ISSUE THREAD

**Issue by btopro** [BrightspaceUI/documentation#44]
Not sure who or how best to get in touch so we'll try here. We're building all our elements for edtech out in the open under the name space of [LRN](https://github.com/LRNWebComponents). We have an [ontology](https://github.com/LRNWebComponents/ontology) repo with our methodology with many elements in existence and more to come. Not sure if it would be worth coordinating but I at least wanted to put it out there since we're going to be building some overlapping things and ours for the most part are very generalizable to putting educational materials online. For example our [lrn-table](https://github.com/LRNWebComponents/lrn-table) hits on a common pain point for instructional designers and faculty members in getting a table of information presented in a highly accessible way.

**Comment by dlockhart** [comment]
Hi Bryan -- I've replied via email. :)
